2024-05-15 03:39:15,234 - apscheduler.scheduler - INFO - Scheduler started
2024-05-15 03:41:53,597 - apscheduler.scheduler - INFO - Scheduler started
2024-05-15 03:42:15,410 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/dershtal/.local/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/dershtal/.local/lib/python3.10/site-packages/telegram/ext/conversationhandler.py", line 626, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/home/dershtal/.local/lib/python3.10/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/home/dershtal/Project/devops_bot/bot/bot.py", line 142, in confirm_savepn
    email_address = context.user_data['email_address']
KeyError: 'email_address'
2024-05-15 03:49:52,739 - apscheduler.scheduler - INFO - Scheduler started
2024-05-15 03:50:14,116 - __main__ - ERROR - Database error: connection to server at "192.168.217.154", port 5432 failed: No route to host
	Is the server running on that host and accepting TCP/IP connections?

2024-05-15 03:50:17,536 - __main__ - ERROR - Database error: connection to server at "192.168.217.154", port 5432 failed: No route to host
	Is the server running on that host and accepting TCP/IP connections?

2024-05-15 03:50:34,507 - apscheduler.scheduler - INFO - Scheduler started
2024-05-15 03:50:53,248 - __main__ - ERROR - Database error: connection to server at "192.168.217.154", port 5432 failed: No route to host
	Is the server running on that host and accepting TCP/IP connections?

2024-05-15 03:51:50,466 - apscheduler.scheduler - INFO - Scheduler started
2024-05-15 03:54:51,504 - apscheduler.scheduler - INFO - Scheduler started
